before_install:
- gem update --system
- gem install sass --version "=3.3.7"
- gem install compass --version "=0.12.3"
- npm install -g grunt-cli bower
- bower install
after_success:
- grunt gh-pages
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
language: node_js
node_js:
- '0.10'
notifications:
  email: false
  slack:
    secure: czu8WPyGKrdTFuZIDq4xmEXtXdXV3qFhsXZHzqD+EGUog4qPrJTR/osCkXQxY4ogCorSHT5Zme4oMeExOsjO6PdqXLt74O/hAf3lFEFzoOgCnRwWrePjzsnaVuYcBzwO24prsXmEbEShf6ho6Sckg6hZKDQK934E/scDH7IuNb0=
env:
  global:
  - secure: NeGM+ZxS9z8ZUfIwAa/1Zy1ZLkwW+aSy09Y/pTZTqGuo3eUR9wAJz+fZrHJLqEOBmOX/GxWVVqMj9Fcx7bkp1AadSbZWnKbDdgW0kt3VQMHhisjTYMFXdFWQB1R6puLQB3IwBpmRfdm1i376KTvpcVUTLdnxBur5b1Uf4MWvKls=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  api_key:
    secure: TxJ0WVWd51fryfgYNP/g2fn8Y07i5irPSuLWumVijpP60/yprrTawI7ZElo7Su8ivA4PX+TD4jJMQQnWjJm5lc9040Q4aKmSYlE42wyLEd7EMCXqdfQK/rXosmtkSMO2iCj5WyxoeOOKYBg08w6VUq+JtgYdIbclhHET4CgtjEw=
  on:
    all_branches: true
    tags: true
sudo: false
cache:
  directories:
  - node_modules
